### ISSUE TITLE
Allow for reusing buffer in block compression

### ISSUE THREAD

**Issue by CosmicHorrorDev** [PSeitz/lz4_flex#102]
Currently the block (de)compression functions return a freshly allocated `Vec` per call. A common alternative when designing an API for putting data somewhere is to take a `output: &mut Vec<u8>` so that you can reuse the same buffer over multiple calls

This would be a breaking change, but shouldn't affect performance in the existing benchmarks

**Comment by PSeitz** [comment]
That's already possible with `lz4_flex::block::compress_into`

**Comment by CosmicHorrorDev** [comment]
That only works if `output` is already large enough to hold the result. A `&mut Vec<u8>` can be resized larger

**Comment by PSeitz** [comment]
Yes you need to call `buffer.resize(get_maximum_output_size(input), 0)` before calling `compress_into`

**Comment by CosmicHorrorDev** [comment]
Ah I forgot that `get_maximum_output_size()` is public. It's a bit clunky, but works so I'll go ahead and close
