### ISSUE TITLE
[trivial] Benchmark charts in README.md are unreadable in GitHub's new dark theme

### ISSUE THREAD

**Issue by mrec** [PSeitz/lz4_flex#12]
The SVGs have transparent backgrounds, so we end up with black text against very dark grey.

(Dark theme is switchable under Settings/Appearance)

**Comment by PSeitz** [comment]
The svgs are generated by criterion and have no background defined. if you click on them they should be rendered fine

**Comment by PSeitz** [comment]
The new images have a background
