### ISSUE TITLE
It would be useful if `get_maximum_output_size()` were a const function

### ISSUE THREAD

**Issue by hellertime** [PSeitz/lz4_flex#152]
It appears there is nothing that prevents `get_maximum_output_size` from being declared const, and if it were then it should be possible to use it in array initializers:

`let buf = [u8; lz4_flex::block::compress::get_maximum_output_size(&input)];`

**Comment by PSeitz** [comment]
Seems like a good idea if you know the size of your input, released with `0.11.3`.

Stack allocation may be slower tough in some cases.
