### ISSUE TITLE
How are we supposed to use the external dict

### ISSUE THREAD

**Issue by irevoire** [PSeitz/lz4_flex#162]
Hello,

I was looking for a compression crate where I can share an external dictionary between a lot of very small entries.
This one seems promising, but I don’t understand how it works.
I can see there are methods to compress and uncompress my data with an external dictionary like this one: https://docs.rs/lz4_flex/0.11.3/lz4_flex/block/fn.compress_with_dict.html
But I don't see any explanation of how I’m supposed to generate the dictionary in the first place?

**Comment by PSeitz** [comment]
The dict is very trivial in lz4, it's just a `&[u8]` to lookup for duplicates, there's no encoding.

**Comment by irevoire** [comment]
I am not sure I understand. Do you have examples somewhere?

**Comment by PSeitz** [comment]
> I am not sure I understand. Do you have examples somewhere?

you could just use the first entry as dictionary

**Comment by paddor** [comment]
You might be interested in [lz4rip](https://github.com/paddor/lz4rip). It has C lz4 perf and first-class dict support, including a dict trainer (COVER algorithm) that should yield the optimal dict.
