### ISSUE TITLE
Integrate into OSS Fuzz

### ISSUE THREAD

**Issue by LeoDog896** [PSeitz/lz4_flex#171]
This project could benefit from constant fuzzing by [Google's OSS Fuzz](https://github.com/google/oss-fuzz) for security vulnerabilities. I would be open to working on this if this is approved.

**Comment by PSeitz** [comment]
Yes, seems like a good idea. There's some fuzzing already which runs in CI.

**Comment by LeoDog896** [comment]
Done in https://github.com/google/oss-fuzz/commit/51d06f6493dbf106f21b09f3da4b5baa60faff7f.
