### ISSUE TITLE
Not actually no_std compatible

### ISSUE THREAD

**Issue by cbiffle** [PSeitz/lz4_flex#29]
The project readme mentions no_std compatibility, but std types are used pervasively, including allocation and `std::io`. Are there plans to fix this? (The commit that said it provided no_std compatibility did nothing of the sort.)

**Comment by PSeitz** [comment]
Hi,

the project is no_std compatible, but only without the frame feature, since frames use io::Write, which is not in core currently.

This should be no_std compatible
`lz4_flex = { version = "0.9.0", default-features = false, features = ["checked-decode"] }`

**Comment by PSeitz** [comment]
I'll close this, feel free to reopen if you have issues with no_std
