### ISSUE TITLE
safe-decode no longer `no_std` compatible

### ISSUE THREAD

**Issue by CraftSpider** [PSeitz/lz4_flex#30]
As of a recent update, using the feature `safe-decode` causes the crate to fail to compile in no_std environments. There are two reported errors:
- Macro `vec!` isn't imported in `decompress_safe.rs`
- Type `Vec` isn't found in `sink.rs` function `vec_sink_for_compression`

**Comment by PSeitz** [comment]
Thanks for the the bug report, it is fixed with https://github.com/PSeitz/lz4_flex/pull/32.
I also added a gh action step to ensure it won't break again.

**Comment by PSeitz** [comment]
Released with 0.9.1, can you confirm it works?

**Comment by CraftSpider** [comment]
Confirmed, everything is building again, thakns for the quick response.
