### ISSUE TITLE
Undefined Behavior with dict and pointer arithmetic

### ISSUE THREAD

**Issue by PSeitz** [PSeitz/lz4_flex#49]
The add method on  https://doc.rust-lang.org/std/primitive.pointer.html#safety-5 mentions that:

"Both the starting and resulting pointer must be either in bounds or one byte past the end of the same [allocated object](https://doc.rust-lang.org/std/ptr/index.html#allocated-object)."

But there are several places, where pointer arithmetic is used to move outside an allocated object.

`MIRIFLAGS="-Zmiri-disable-isolation -Zmiri-disable-stacked-borrows" cargo +nightly miri test --no-default-features` fails for dict tests currently

@arthurprs

**Comment by arthurprs** [comment]
Oh wow, rust unsafe rules are really depressing :sweat_smile: I can try and cook a fix soon.

**Comment by PSeitz** [comment]
hehe they are quite strict, but I think they are just better in documenting it. I read the same applies for C (in a Rust thread though).

There are several places where `ptr.add` to check out of bounds. I think they can to be replace with a cast to usize or wrapping_add`, which is oddly not unsafe until dereferencing. 

I also saw a suspicious comment:
` // match crosses ext_dict and output`
