### ISSUE TITLE
Streaming compression/decompression?

### ISSUE THREAD

**Issue by coolreader18** [PSeitz/lz4_flex#6]
Would it be possible to expose a type that implements streaming de/compression, e.g. a streaming decompressor that implements `Read`?

**Comment by PSeitz** [comment]
Good point, I planned that streaming could be part of the frame format, which is currently not yet implemented.

The block implementation currently preallocates memory in compression and decompression for performance reasons, which makes it impractical for streaming. Creating a `Read` wrapper around it would be easy, although not terribly efficient with the preallocation.

**Comment by coolreader18** [comment]
It might not actually even be necessary; I'm looking to replace lz-fear since I think this is faster based off of [this](https://blog.logrocket.com/rust-compression-libraries/) post, maybe it's fast enough that accurate preallocation w/o streaming is still faster than lz-fear using streaming.

**Comment by PSeitz** [comment]
lz-fear is actually part of the benchmark in this lib, you can run it with `cargo bench`. I included it to verify the claims to be as fast as the cpp implementation, which appear not to be true. The results are in the readme:

https://github.com/PSeitz/lz4_flex#benchmarks

**Comment by coolreader18** [comment]
Yep, turns out streaming isn't even necessary :)

```
Benchmark #1: ./rustpython-norm -c ""
  Time (mean ± σ):      53.1 ms ±  13.2 ms    [User: 45.4 ms, System: 7.3 ms]
  Range (min … max):    36.3 ms …  77.2 ms    66 runs
 
Benchmark #2: ./rustpython-opt -c ""
  Time (mean ± σ):      15.2 ms ±   7.4 ms    [User: 11.0 ms, System: 4.2 ms]
  Range (min … max):     7.7 ms …  33.8 ms    206 runs
 
Summary
  './rustpython-opt -c ""' ran
    3.50 ± 1.92 times faster than './rustpython-norm -c ""'
```

We decompress about 340K bytes (I think) on startup and parse it with bincode, so this is definitely really nice, thanks for working on this library!

**Comment by PSeitz** [comment]
Awesome, love to hear that it's useful
