### ISSUE TITLE
Reader / Writer API

### ISSUE THREAD

**Issue by Timmmm** [PSeitz/lz4_flex#60]
It would be nice to have a Reader / Writer API to avoid having to read everything into memory. The C wrapper crate has this:

https://docs.rs/lz4/latest/lz4/struct.Decoder.html

**Comment by PSeitz** [comment]
lz4_flex also has that via the `FrameDecoder` and `FrameEncoder`. It's even mentioned in the first sentences https://docs.rs/lz4_flex/latest/lz4_flex/

**Comment by Timmmm** [comment]
Oh yeah totally missed that, sorry.
